server:
  port: 8000

spring:
  application:
    name: pandemic
  jackson:
    date-format: YYYY-MM-DD HH:mm:ss
    time-zone: GMT+8
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/covid
    username: root
    password: bonjouroumar200

  profiles:
    active: dev
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 5000
      filter:
        stat:
          enabled: true
          db-type: mysql
          log-slow-sql: false
          slow-sql-millis: 2000
      web-stat-filter:
        enabled: true
        exclusions:
          - "*.js"
          - "*.gif"
          - "*.jpg"
          - "*.png"
          - "*.css"
          - "*.ico"
          - "/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: root
        login-password: bonjouroumar200
        allow:

token:
  head: Authorization
  expireTime: 86400
  secret: ^_^.[diallo].^_^

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      #开启Mybatis下划线命名转驼峰命名
mybatis:
  configuration:
    map-underscore-to-camel-case: true


  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.alpha.pandemic.models

alioss:
  endpoint: oss-cn-shanghai.aliyuncs.com
  accessKeyId: LTAI5tLDnEpVEQ2bMGAawHPd
  accessKeySecret: fbqOJjK9q0ijBuDdEGojyjyB8v8jaA
  bucketName: diallo
